### ISSUE TITLE
Bonelab breaks on launch with fusion

### ISSUE THREAD

**Issue by Forze14** [Lakatrazz/BONELAB-Fusion#10]
Ive been having alot of issues with many code mods but Fusion makes bonelab unplayable, when i launch into the menu void or whatever i cannot move whatsoever, my avatar has been bent into a stretched broken mess, and the menu screen displays everything from the settings to the developer mode screen, i can remove these and load into a level but im still frozen and bent into a disturbing mess

**Comment by jfranecki** [comment]
I'm having the same exact issue. https://github.com/Lakatrazz/BONELAB-Fusion/issues/9

**Comment by jfranecki** [comment]
I believe it has something to do with this line of code [here](https://github.com/Lakatrazz/BONELAB-Fusion/blob/main/LabFusion.csproj#L390).

Two lines that stuck out to me in my log file were:
`[LabFusion] [ERROR] HarmonyLib.HarmonyException: Patching exception in method null ---> System.ArgumentException: Undefined target method for patch method static void LabFusion.Patching.RemapRigPatches::JumpCharge(SLZ.Rig.RemapRig __instance, float deltaTime, bool chargeInput, bool __state)

[ERROR] Exception in Harmony patch of method void SLZ.VRMK.Avatar::RefreshBodyMeasurements():`

Both seem to relate to the player model which is why our avatars seems to be bent into a stretched broken mess unable to move.

**Comment by noclipgames** [comment]
did you get patch 3/public beta?

**Comment by Forze14** [comment]
> 

Nope, i will try this

**Comment by DINOTICK-Dev** [comment]
Hello! Please swap to the "patch 3" on Steam or Oculus
(On steam click on the gear, preferences, betas, and set it to patch 3)

**Comment by zurgeg** [comment]
> Hello! Please swap to the "patch 3" on Steam or Oculus (On steam click on the gear, preferences, betas, and set it to patch 3)

For me it was named "public_beta" and not "patch 3"

**Comment by Lakatrazz** [comment]
This is due to not being on the beta branch
